export const playwrightVersion = '1.30.0'
export const yarnVersion = '3.3.1'
export const fixture = 'plaited-workshop-fixture'
export const storiesRoutePath = 'GET@/_story-paths'
export const testsRoutePath = '_tests'
