blank_issues_enabled: false
contact_links:
  - name: Questions and discussions
    url: https://github.com/orgs/plaited/discussions
    about: Use Discussions for open-ended questions or conversation.
