export const ASSERTION_ERROR = 'ASSERTION_ERROR'
export const UNKNOWN_ERROR = 'UNKNOWN_ERROR'
export const TIMEOUT_ERROR = 'TIMEOUT_ERROR'
export const MISSING_TEST_PARAMS_ERROR = 'MISSING_TEST_PARAMS_ERROR'
export const TEST_PASSED = 'TEST_PASSED'
export const TEST_EXCEPTION = 'TEST_EXCEPTION'
export const DEFAULT_PLAY_TIMEOUT = 5_000
