export const stopResetTrigger = 'click->stop-reset'
export const startTrigger = 'click->start'
export const add30Trigger = 'click->add-30'
export const addToTimeArray = 'add to time array'
export const add30Seconds = 'add 30 seconds'
export const startClock = 'start clock'
export const pauseClock = 'pause clock'
export const resetClock = 'reset clock'
