import { keyMirror } from '../utils'

export const CLIENT_EVENTS = keyMirror(
  'TOOLS_DISCOVERED',
  'RESOURCES_DISCOVERED',
  'PROMPTS_DISCOVERED',
  'RESOURCE_TEMPLATES_DISCOVERED',
)
export const CLIENT_ERROR_EVENTS = keyMirror(
  'ERROR_LIST_TOOLS',
  'ERROR_LIST_RESOURCES',
  'ERROR_LIST_RESOURCE_TEMPLATES',
  'ERROR_LIST_PROMPTS',
  'ERROR_DISCOVER_PRIMITIVES',
  'ERROR_ADD_SERVER_TO_REGISTERED_SERVERS',
  'ERROR_REGISTERING_SERVERS',
)
