export {
  createLocalAdapter,
  type LocalAdapterOptions,
} from './improve/distillation-adapter.ts'

export {
  commitExperiment,
  discardExperiment,
  type ExperimentEntry,
  getBaseline,
  loadExperiments,
  logExperiment,
} from './improve/git-experiment.ts'

export {
  type EvaluationTarget,
  EvaluationTargetSchema,
  type RepoImprovementJudgeInput,
  RepoImprovementJudgeInputSchema,
  type RepoImprovementJudgeOutcome,
  RepoImprovementJudgeOutcomeSchema,
  type RepoImprovementJudgeRubric,
  RepoImprovementJudgeRubricSchema,
  type RepoImprovementMetaVerifierOutcome,
  RepoImprovementMetaVerifierOutcomeSchema,
  type RepoImprovementMetaVerifierRubric,
  RepoImprovementMetaVerifierRubricSchema,
  type RetainedOutputSuitability,
  type RetainedOutputSuitabilityLabel,
  RetainedOutputSuitabilityLabelSchema,
  RetainedOutputSuitabilitySchema,
  type TrialJudgeInput,
  TrialJudgeInputSchema,
  type TrialJudgeOutcome,
  TrialJudgeOutcomeSchema,
  type TrialJudgeResult,
  TrialJudgeResultSchema,
  type TrialMetaVerifierInput,
  TrialMetaVerifierInputSchema,
  type TrialMetaVerifierOutcome,
  TrialMetaVerifierOutcomeSchema,
  type TrialMetaVerifierTrustLabel,
  TrialMetaVerifierTrustLabelSchema,
} from './improve/judge-contracts.ts'

export {
  DecisionStepSchema,
  GradingDimensionsSchema,
  type MetaVerification,
  MetaVerificationSchema,
  type TrainingAssessmentReason,
  TrainingAssessmentReasonSchema,
  type TrainingCandidateAssessment,
  TrainingCandidateAssessmentSchema,
  type TrainingCaptureAssessment,
  TrainingCaptureAssessmentSchema,
  type TrainingCaptureReason,
  TrainingCaptureReasonSchema,
  type TrainingScore,
  type TrainingScoreInput,
  TrainingScoreInputSchema,
  TrainingScoreOutputSchema,
  TrainingScoreSchema,
} from './improve/training.schemas.ts'

export {
  type AssessTrainingCandidateOptions,
  type AssessTrainingCaptureOptions,
  assessTrainingCandidate,
  assessTrainingCapture,
  collectTrainingCandidates,
  computeTrainingWeight,
  scoreTrainingDimensions,
  type TrainingDataCandidate,
  trainingScoreCli,
  withStatisticalVerification,
} from './improve/training.ts'
export {
  DEFAULT_K,
  DEFAULT_TIMEOUT,
} from './improve/trial.constants.ts'
export {
  type Adapter,
  type AdapterInput,
  AdapterInputSchema,
  type AdapterResult,
  AdapterResultSchema,
  type CaptureEvidence,
  CaptureEvidenceSchema,
  type CaptureSnippet,
  CaptureSnippetSchema,
  type Grader,
  type GraderResult,
  GraderResultSchema,
  type GradingDimensions,
  type PromptCase,
  PromptCaseSchema,
  type Timing,
  TimingSchema,
  type TrajectoryRichness,
  TrajectoryRichnessSchema,
  type TrajectoryStep,
  TrajectoryStepSchema,
  type TrialEntry,
  TrialEntrySchema,
  type TrialResult,
  TrialResultSchema,
} from './improve/trial.schemas.ts'
export {
  calculatePassAtK,
  calculatePassExpK,
  runTrial,
  type TrialConfig,
  TrialInputSchema,
  TrialOutputSchema,
  trialCli,
} from './improve/trial.ts'
export {
  loadAdapter,
  loadGrader,
  loadJsonl,
  loadPrompts,
  persistTrialResults,
  type Verifier,
  withMetaVerification,
} from './improve/trial.utils.ts'
export {
  formatTrialSummary,
  summarizeTrialResults,
  type TrialPromptSummary,
  type TrialRunSummary,
  type TrialThemeSummary,
} from './improve/trial-report.ts'
