name: build/tests

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            yarn install
            npx playwright install
            yarn run build
            yarn run test
  update-typedocs:
    runs-on: ubuntu-22.04
    needs: [check]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Git config
        run:  |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build Docs
        run: |
          yarn install
          yarn run build
          yarn run typedocs
      - name: Push new typedocs
        run:  |
            git add playbook/api
            git commit -m "typedocs [skip ci]"
            git push origin HEAD
     
