name: Check and update typedocs

on:
  push:
    branches:
      - main

jobs:
  check:
    
    runs-on: ubuntu-22.04
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            bun install
            bun run build
            bun run test
            bun run docs
      - name: Git Config
        run:  |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor}}@users.noreply.github.com"
          - name: Git Config
      - name: Push new typedocs
        run:  |
            git add playbook/libraries
            git commit -m "docs(playbook): update typedocs"
            git push origin origin main

