name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    
    runs-on: ubuntu-22.04
    
    steps:
    
    - uses: actions/checkout@v3
    - name: Build the stack
      run: docker-compose up -d
    - name: Lint
      run: docker-compose run --rm deno task lint
    - name: Test
      run: docker-compose run --rm deno task test:ci
