name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version tag (e.g., 1.0.0)'
        required: true
      otp:
        description: ''
        required: true

jobs:
  check:
    
    runs-on: ubuntu-22.04
    
    steps:
    
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git user
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
      
      - name: Validate input version
        run: |
          version="${{ github.event.inputs.version }}"
          if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(-([a-zA-Z0-9_-]+))?$ ]]; then
            echo "Error: Version must have the format 'x.y.z' or 'x.y.z-<string>', where x, y, and z are numbers."
            exit 1
          fi

      - name: Test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: zsh test.sh

      - name: Publish
        uses: devcontainers/ci@v0.3
        with:
          runCmd: bun lerna publish ${{ github.event.inputs.version }} --otp ${{ github.event.inputs.otp }} --no-git-reset --no-private --exact

      - name: Create and push new tag
        run: |
          git add .
          git commit -m "ci:  update gitHead on manifests for ${{ github.event.inputs.version }}"
          git push origin ${{ github.event.inputs.version }}