name: Tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version tag (e.g., 1.0.0)'
        required: true

jobs:
  push_tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure Git user
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"

    - name: Validate input version
      run: |
        version="${{ github.event.inputs.version }}"
        if [[ ! $version =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)(?:-([a-zA-Z0-9_-]+))?$ ]]; then
          echo "Error: Version must have the format 'x.y.z' or 'x.y.z-<string>', where x, y, and z are numbers."
          exit 1
        fi

    - name: Check if tag already exists and compare with the latest tag
      run: |
        git fetch --tags
        if git rev-parse ${{ github.event.inputs.version }} >/dev/null 2>&1; then
          echo "Error: Tag already exists."
          exit 1
        fi

        latest_tag=$(git tag --list --sort=-version:refname | grep -P "^[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9_-]+)?$" | head -n 1)
        if [ ! -z "$latest_tag" ] && [[ $latest_tag > ${{ github.event.inputs.version }} ]]; then
          echo "Error: The new tag version must be greater than the last tag on the remote."
          exit 1
        fi

    - name: Create and push new tag
      run: |
        git tag ${{ github.event.inputs.version }}
        git push origin ${{ github.event.inputs.version }}
